### ISSUE TITLE
4 LOGO DESIGN Proposal for Steem Ax

### ISSUE THREAD

**Issue by chrisjasonoswa** [ArtoLabs/SteemAX#2]
I have observed that Steem Ax does not have a logo yet. So I made a logo proposal for this project.
To have more choices, I made 4 logo styles for Steem Ax. The 4 logo styles has 2 colors. As seen on the logos, I made use of the upvote symbol  since Steem AX is an auto-upvote exchange. So here are the 4 logos that I made.
![steemax](https://user-images.githubusercontent.com/38552359/40265338-e75303dc-5b68-11e8-953b-6390cd6707f5.png)

![steemax2](https://user-images.githubusercontent.com/38552359/40265307-8a5b9324-5b68-11e8-974a-6997c25c8de0.png)

<b>I will provide the full color version and the ready to use png of the logo that you like the most </b>

**Comment by ArtoLabs** [comment]
Chris, so sorry this is the first time I'm seeing this. I really like the designs. SteemAX does not allow the user to directly upvote as it is an auto upvote system so no upvote button or logo design is needed. As for the logos at the very top, perhaps we can discuss a combination of what you have. Are you part of utopian.io? Let's talk. You can find my discord channel on my website https://mike.artopium.com

**Comment by chrisjasonoswa** [comment]
Your discord invite in your browser has expired sir.. i have left a message in your fb.Thank you
